name: TriageOps

on:
  pull_request_target:
    types:
      - opened
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}"
        dot: true
  contributor-manual-deploy:
    if: github.event_name == "pull_request_target" && github.event.user.type != "Bot" && github.event.user.login != "RecapTimeBot"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        gh issue comment ${{ github.event.number }} --body-file .github/automated-replies/manual-review-required.md
      env:
        GITHUB_TOKEN: ${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}